"""
Data modules and interfaces for the Boti pipeline context.
"""

from boti_data.db import (
    AsyncSqlDatabaseResource,
    BuilderConfig,
    DefaultBase,
    EngineRegistry,
    RegistryConfig,
    SqlAlchemyModelBuilder,
    SqlDatabaseConfig,
    SqlDatabaseResource,
    SqlPartitionPlan,
    SqlPartitionSpec,
    SqlPartitionedLoadRequest,
    SqlPartitionedLoader,
    SqlModelRegistry,
    ensure_greenlet_available,
    get_global_registry,
)
from boti_data.connection_catalog import ConnectionCatalog
from boti_data.parquet import ParquetDataConfig, ParquetDataResource, ParquetReader
from boti_data.filters import (
    FilterHandler,
    Expr,
    TrueExpr,
    And,
    Or,
    Not,
)
from boti_data.gateway import DataGateway, ParquetLoadRequest, SqlLoadRequest
from boti_data.helper import DataHelper
from boti_data.field_map import FieldMap
from boti_data.gateway import DataFrameOptions, DataFrameParams
from boti_data.joins import indexed_left_join, left_join_frames
from boti_data.schema import (
    SchemaValidationError,
    align_frames_for_join,
    apply_schema_map,
    infer_schema_map,
    normalize_dtype_alias,
    normalize_schema_map,
    validate_schema,
)
from boti_data.datacube import DatacubeConfig, DatacubeContract
from boti_data.dataset import HybridDataset
from boti_data.enrichment import AsyncFrameEnricher, AttachmentSpec, FrameEnricher
from boti_data.pipelines import (
    CsvSink,
    CsvSinkConfig,
    JsonlSink,
    JsonlSinkConfig,
    ParquetMaterializationResult,
    ParquetPipeline,
    ParquetSink,
    SinkPipeline,
    SinkRegistry,
    SinkWriteResult,
    available_sinks,
    create_sink,
    register_sink,
)
from boti_data.watermark import (
    FileWatermarkStore,
    FsspecWatermarkStore,
    IncrementalResult,
    WatermarkStore,
    advance_watermark,
    build_incremental_filters,
)

__all__ = [
    "And",
    "AsyncFrameEnricher",
    "AsyncSqlDatabaseResource",
    "AttachmentSpec",
    "BuilderConfig",
    "ConnectionCatalog",
    "CsvSink",
    "CsvSinkConfig",
    "DataFrameOptions",
    "DataFrameParams",
    "DataGateway",
    "DataHelper",
    "DatacubeConfig",
    "DatacubeContract",
    "DefaultBase",
    "EngineRegistry",
    "Expr",
    "FieldMap",
    "FileWatermarkStore",
    "FsspecWatermarkStore",
    "FilterHandler",
    "FrameEnricher",
    "HybridDataset",
    "IncrementalResult",
    "JsonlSink",
    "JsonlSinkConfig",
    "Not",
    "Or",
    "ParquetDataConfig",
    "ParquetLoadRequest",
    "ParquetDataResource",
    "ParquetMaterializationResult",
    "ParquetPipeline",
    "ParquetReader",
    "ParquetSink",
    "RegistryConfig",
    "SchemaValidationError",
    "SinkPipeline",
    "SinkRegistry",
    "SinkWriteResult",
    "SqlLoadRequest",
    "SqlAlchemyModelBuilder",
    "SqlDatabaseConfig",
    "SqlDatabaseResource",
    "SqlPartitionPlan",
    "SqlPartitionSpec",
    "SqlPartitionedLoadRequest",
    "SqlPartitionedLoader",
    "SqlModelRegistry",
    "TrueExpr",
    "WatermarkStore",
    "advance_watermark",
    "align_frames_for_join",
    "apply_schema_map",
    "available_sinks",
    "build_incremental_filters",
    "create_sink",
    "ensure_greenlet_available",
    "get_global_registry",
    "indexed_left_join",
    "infer_schema_map",
    "left_join_frames",
    "normalize_dtype_alias",
    "normalize_schema_map",
    "register_sink",
    "validate_schema",
]
