"""
Data modules and interfaces for the Boti pipeline context.
"""

from __future__ import annotations

import importlib
from typing import Any

__all__ = [
    "And",
    "AsyncFrameEnricher",
    "AsyncSqlDatabaseResource",
    "AsyncSqlRepository",
    "AsyncSqlUnitOfWork",
    "AttachmentSpec",
    "BaseDataCube",
    "BaseArtifact",
    "BuilderConfig",
    "ConnectionCatalog",
    "CsvSink",
    "CsvSinkConfig",
    "DataFrameOptions",
    "DataFrameParams",
    "DataGateway",
    "DataHelper",
    "DatacubeConfig",
    "DatacubeContract",
    "DefaultBase",
    "EngineRegistry",
    "Expr",
    "FieldMap",
    "FileWatermarkStore",
    "FsspecWatermarkStore",
    "FilterHandler",
    "FrameEnricher",
    "HybridDataset",
    "IncrementalResult",
    "JsonlSink",
    "JsonlSinkConfig",
    "Not",
    "Or",
    "ParquetDataConfig",
    "ParquetLoadRequest",
    "ParquetDataResource",
    "ParquetMaterializationResult",
    "ParquetPipeline",
    "ParquetReader",
    "ParquetSink",
    "RegistryConfig",
    "SchemaValidationError",
    "SinkPipeline",
    "SinkRegistry",
    "SinkWriteResult",
    "SqlLoadRequest",
    "SqlAlchemyModelBuilder",
    "SqlDatabaseConfig",
    "SqlDatabaseResource",
    "SqlPartitionPlan",
    "SqlPartitionSpec",
    "SqlPartitionedLoadRequest",
    "SqlPartitionedLoader",
    "SqlModelRegistry",
    "SqlRepository",
    "SqlUnitOfWork",
    "TrueExpr",
    "VectorMetric",
    "WatermarkStore",
    "advance_watermark",
    "align_frames_for_join",
    "apply_schema_map",
    "available_sinks",
    "build_incremental_filters",
    "create_sink",
    "ensure_greenlet_available",
    "get_global_registry",
    "indexed_left_join",
    "infer_schema_map",
    "left_join_frames",
    "nearest_neighbors",
    "normalize_dtype_alias",
    "normalize_schema_map",
    "register_sink",
    "validate_schema",
    "vector_distance",
]

# Every public name is loaded lazily (PEP 562) so that importing boti_data (or
# any of its dependency-clean pieces, e.g. SqlRepository) never pulls in the
# dask/pandas/polars/pyarrow chain used by the dataframe-shaped, bulk-oriented
# side of the package (DataGateway/DataHelper, ParquetPipeline, etc.) unless a
# consumer actually touches one of those names.
_LAZY = {
    # db.* — dependency-clean.
    "AsyncSqlDatabaseResource": ("boti_data.db.sql_manager", "AsyncSqlDatabaseResource"),
    "EngineRegistry": ("boti_data.db.sql_manager", "EngineRegistry"),
    "SqlDatabaseConfig": ("boti_data.db.sql_manager", "SqlDatabaseConfig"),
    "SqlDatabaseResource": ("boti_data.db.sql_manager", "SqlDatabaseResource"),
    "BuilderConfig": ("boti_data.db.sql_model_builder", "BuilderConfig"),
    "SqlAlchemyModelBuilder": ("boti_data.db.sql_model_builder", "SqlAlchemyModelBuilder"),
    "DefaultBase": ("boti_data.db.sql_model_registry", "DefaultBase"),
    "RegistryConfig": ("boti_data.db.sql_model_registry", "RegistryConfig"),
    "SqlModelRegistry": ("boti_data.db.sql_model_registry", "SqlModelRegistry"),
    "get_global_registry": ("boti_data.db.sql_model_registry", "get_global_registry"),
    "ensure_greenlet_available": ("boti_data.db.sqlalchemy_async", "ensure_greenlet_available"),
    "SqlPartitionPlan": ("boti_data.db.partitioned_types", "SqlPartitionPlan"),
    "SqlPartitionSpec": ("boti_data.db.partitioned_types", "SqlPartitionSpec"),
    "SqlRepository": ("boti_data.db.sql_repository", "SqlRepository"),
    "AsyncSqlRepository": ("boti_data.db.sql_repository", "AsyncSqlRepository"),
    "SqlUnitOfWork": ("boti_data.db.sql_repository", "SqlUnitOfWork"),
    "AsyncSqlUnitOfWork": ("boti_data.db.sql_repository", "AsyncSqlUnitOfWork"),
    "nearest_neighbors": ("boti_data.db.vector_search", "nearest_neighbors"),
    "vector_distance": ("boti_data.db.vector_search", "vector_distance"),
    "VectorMetric": ("boti_data.db.vector_search", "VectorMetric"),
    "FieldMap": ("boti_data.field_map", "FieldMap"),
    # dask+pandas — the one heavy import inside the otherwise-clean db package.
    "SqlPartitionedLoader": ("boti_data.db.partitioned_loader", "SqlPartitionedLoader"),
    "SqlPartitionedLoadRequest": ("boti_data.db.partitioned_loader", "SqlPartitionedLoadRequest"),
    # dask/pandas/polars/pyarrow-touching — the dataframe-shaped, bulk-oriented side.
    "ConnectionCatalog": ("boti_data.connection_catalog", "ConnectionCatalog"),
    "ParquetDataConfig": ("boti_data.parquet", "ParquetDataConfig"),
    "ParquetDataResource": ("boti_data.parquet", "ParquetDataResource"),
    "ParquetReader": ("boti_data.parquet", "ParquetReader"),
    "FilterHandler": ("boti_data.filters", "FilterHandler"),
    "Expr": ("boti_data.filters", "Expr"),
    "TrueExpr": ("boti_data.filters", "TrueExpr"),
    "And": ("boti_data.filters", "And"),
    "Or": ("boti_data.filters", "Or"),
    "Not": ("boti_data.filters", "Not"),
    "DataGateway": ("boti_data.gateway", "DataGateway"),
    "ParquetLoadRequest": ("boti_data.gateway", "ParquetLoadRequest"),
    "SqlLoadRequest": ("boti_data.gateway", "SqlLoadRequest"),
    "DataFrameOptions": ("boti_data.gateway", "DataFrameOptions"),
    "DataFrameParams": ("boti_data.gateway", "DataFrameParams"),
    "DataHelper": ("boti_data.helper", "DataHelper"),
    "indexed_left_join": ("boti_data.joins", "indexed_left_join"),
    "left_join_frames": ("boti_data.joins", "left_join_frames"),
    "SchemaValidationError": ("boti_data.schema", "SchemaValidationError"),
    "align_frames_for_join": ("boti_data.schema", "align_frames_for_join"),
    "apply_schema_map": ("boti_data.schema", "apply_schema_map"),
    "infer_schema_map": ("boti_data.schema", "infer_schema_map"),
    "normalize_dtype_alias": ("boti_data.schema", "normalize_dtype_alias"),
    "normalize_schema_map": ("boti_data.schema", "normalize_schema_map"),
    "validate_schema": ("boti_data.schema", "validate_schema"),
    "BaseDataCube": ("boti_data.datacube", "BaseDataCube"),
    "BaseArtifact": ("boti_data.datacube", "BaseArtifact"),
    "DatacubeConfig": ("boti_data.datacube", "DatacubeConfig"),
    "DatacubeContract": ("boti_data.datacube", "DatacubeContract"),
    "HybridDataset": ("boti_data.dataset", "HybridDataset"),
    "AsyncFrameEnricher": ("boti_data.enrichment", "AsyncFrameEnricher"),
    "AttachmentSpec": ("boti_data.enrichment", "AttachmentSpec"),
    "FrameEnricher": ("boti_data.enrichment", "FrameEnricher"),
    "CsvSink": ("boti_data.pipelines", "CsvSink"),
    "CsvSinkConfig": ("boti_data.pipelines", "CsvSinkConfig"),
    "JsonlSink": ("boti_data.pipelines", "JsonlSink"),
    "JsonlSinkConfig": ("boti_data.pipelines", "JsonlSinkConfig"),
    "ParquetMaterializationResult": ("boti_data.pipelines", "ParquetMaterializationResult"),
    "ParquetPipeline": ("boti_data.pipelines", "ParquetPipeline"),
    "ParquetSink": ("boti_data.pipelines", "ParquetSink"),
    "SinkPipeline": ("boti_data.pipelines", "SinkPipeline"),
    "SinkRegistry": ("boti_data.pipelines", "SinkRegistry"),
    "SinkWriteResult": ("boti_data.pipelines", "SinkWriteResult"),
    "available_sinks": ("boti_data.pipelines", "available_sinks"),
    "create_sink": ("boti_data.pipelines", "create_sink"),
    "register_sink": ("boti_data.pipelines", "register_sink"),
    "FileWatermarkStore": ("boti_data.watermark", "FileWatermarkStore"),
    "FsspecWatermarkStore": ("boti_data.watermark", "FsspecWatermarkStore"),
    "IncrementalResult": ("boti_data.watermark", "IncrementalResult"),
    "WatermarkStore": ("boti_data.watermark", "WatermarkStore"),
    "advance_watermark": ("boti_data.watermark", "advance_watermark"),
    "build_incremental_filters": ("boti_data.watermark", "build_incremental_filters"),
}


def __getattr__(name: str) -> Any:
    if name in _LAZY:
        module_name, attr = _LAZY[name]
        value = getattr(importlib.import_module(module_name), attr)
        globals()[name] = value
        return value
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
